apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-platform
spec:
  package: hasheddan/crossflux-aws-platform:latest
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
