apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  releaseName: crossplane
  targetNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane-master
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
      version: v1.2.0-rc.0.113.gb94884d0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
