apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  releaseName: crossplane
  targetNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane-master
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
