apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
spec:
  releaseName: crossplane
  targetNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane
      version: 1.2.0-rc.0.113.gb94884d0
      sourceRef:
        kind: HelmRepository
        name: crossplane-master
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
