apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: setup
  sourceRef:
    kind: GitRepository
    name: crossflux
  path: ./platform
  prune: true
  validation: client