apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  # NOTE(hasheddan): we use a relatively short sync period here to make sure
  # that we are able to create any ProviderConfigs after packages are installed.
  interval: 1m0s
  dependsOn:
    - name: setup
  sourceRef:
    kind: GitRepository
    name: crossflux
  path: ./platform
  prune: true
  validation: client
