apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: teams
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: setup
    - name: platform-provider-configs
  sourceRef:
    kind: GitRepository
    name: crossflux
  path: ./teams
  prune: true
  validation: client
